# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: a5250703f572a9811aac
    multiple: false
    tabs: 'file camera url facebook gdrive gphotos instagram'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Page'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'BlogIndex'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
      - file: 'content/pages/contact.md'
        label: 'Contact Page'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - { label: Body, name: body, widget: markdown }
          - { label: Facebook Page, name: facebook, widget: string }
          - { label: Email Address, name: email, widget: string }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      - file: 'content/pages/donate.md'
        label: 'Donate Page'
        name: 'donate'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: DonatePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'components' }
          - { label: Title, name: title, widget: string }
          - { label: 'Background Image', name: backgroundImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - { label: 'Section 1', name: section1, widget: markdown }
          - { label: 'Section 2', name: section2, widget: markdown }
          - { label: 'Section 3', name: section3, widget: markdown }
          - { label: 'Section 4', name: section4, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      - file: 'content/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ComponentsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'components' }
          - { label: Title, name: title, widget: string }
          - { label: 'Background Image', name: backgroundImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - { label: 'Section 1', name: section1, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

       - file: 'content/pages/shop.md'
        label: 'Shop'
        name: 'ShopIndex'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ShopIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'shop' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
      - file: 'content/pages/shop.md'
        label: 'Shop'
        name: 'ShopIndex'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ShopIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'shop' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
 
  - name: posts
    label: Our Animals
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Title, name: title, widget: string }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
      - { label: Date / Order, name: date, widget: date, format: 'YYYY-MM-DD' }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Content, name: body, widget: markdown }
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: items
    label: Our Items
    editor:
      preview: true
    folder: content/items
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SingleItem }
      - { label: Title, name: title, widget: string }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - { label: Content, name: body, widget: markdown }
      - label: 'Categories'
        name: 'itemCategories'
        widget: 'list'
        required: false
        fields:
          - label: 'Category'
            name: 'itemCategory'
            widget: 'relation'
            collection: 'itemCategories'
            searchFields: ['title']
            valueField: 'title'
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: itemCategories
    label: Item Category
    editor:
      preview: false
    folder: content/itemCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: ShopIndex }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: postCategories
    label: Post Category
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: BlogIndex }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
